export const PROVINCES = [
  { value: 'aceh', label: 'Aceh' },
  { value: 'sumatera_utara', label: 'Sumatera Utara' },
  { value: 'sumatera_barat', label: 'Sumatera Barat' },
  { value: 'riau', label: 'Riau' },
  { value: 'kepulauan_riau', label: 'Kepulauan Riau' },
  { value: 'jambi', label: 'Jambi' },
  { value: 'sumatera_selatan', label: 'Sumatera Selatan' },
  { value: 'kepulauan_bangka_belitung', label: 'Kepulauan Bangka Belitung' },
  { value: 'bengkulu', label: 'Bengkulu' },
  { value: 'lampung', label: 'Lampung' },
  { value: 'banten', label: 'Banten' },
  { value: 'dki_jakarta', label: 'DKI Jakarta' },
  { value: 'jawa_barat', label: 'Jawa Barat' },
  { value: 'jawa_tengah', label: 'Jawa Tengah' },
  { value: 'di_yogyakarta', label: 'DI Yogyakarta' },
  { value: 'jawa_timur', label: 'Jawa Timur' },
  { value: 'bali', label: 'Bali' },
  { value: 'nusa_tenggara_barat', label: 'Nusa Tenggara Barat' },
  { value: 'nusa_tenggara_timur', label: 'Nusa Tenggara Timur' },
  { value: 'kalimantan_barat', label: 'Kalimantan Barat' },
  { value: 'kalimantan_tengah', label: 'Kalimantan Tengah' },
  { value: 'kalimantan_selatan', label: 'Kalimantan Selatan' },
  { value: 'kalimantan_timur', label: 'Kalimantan Timur' },
  { value: 'kalimantan_utara', label: 'Kalimantan Utara' },
  { value: 'sulawesi_utara', label: 'Sulawesi Utara' },
  { value: 'gorontalo', label: 'Gorontalo' },
  { value: 'sulawesi_tengah', label: 'Sulawesi Tengah' },
  { value: 'sulawesi_barat', label: 'Sulawesi Barat' },
  { value: 'sulawesi_selatan', label: 'Sulawesi Selatan' },
  { value: 'sulawesi_tenggara', label: 'Sulawesi Tenggara' },
  { value: 'maluku', label: 'Maluku' },
  { value: 'maluku_utara', label: 'Maluku Utara' },
  { value: 'papua_barat', label: 'Papua Barat' },
  { value: 'papua', label: 'Papua' },
  { value: 'papua_selatan', label: 'Papua Selatan' },
  { value: 'papua_tengah', label: 'Papua Tengah' },
  { value: 'papua_pegunungan', label: 'Papua Pegunungan' },
  { value: 'papua_barat_daya', label: 'Papua Barat Daya' },
]

export const CITIES_BY_PROVINCE: Record<
  string,
  { value: string; label: string }[]
> = {
  aceh: [
    { value: 'banda_aceh', label: 'Kota Banda Aceh' },
    { value: 'langsa', label: 'Kota Langsa' },
    { value: 'lhokseumawe', label: 'Kota Lhokseumawe' },
    { value: 'sabang', label: 'Kota Sabang' },
    { value: 'subulussalam', label: 'Kota Subulussalam' },
    { value: 'aceh_besar', label: 'Kab. Aceh Besar' },
    { value: 'aceh_utara', label: 'Kab. Aceh Utara' },
    { value: 'aceh_timur', label: 'Kab. Aceh Timur' },
  ],
  sumatera_utara: [
    { value: 'medan', label: 'Kota Medan' },
    { value: 'binjai', label: 'Kota Binjai' },
    { value: 'pematangsiantar', label: 'Kota Pematangsiantar' },
    { value: 'tebing_tinggi', label: 'Kota Tebing Tinggi' },
    { value: 'padangsidimpuan', label: 'Kota Padangsidimpuan' },
    { value: 'gunungsitoli', label: 'Kota Gunungsitoli' },
    { value: 'deli_serdang', label: 'Kab. Deli Serdang' },
    { value: 'langkat', label: 'Kab. Langkat' },
    { value: 'simalungun', label: 'Kab. Simalungun' },
    { value: 'karo', label: 'Kab. Karo' },
  ],
  sumatera_barat: [
    { value: 'padang', label: 'Kota Padang' },
    { value: 'bukittinggi', label: 'Kota Bukittinggi' },
    { value: 'payakumbuh', label: 'Kota Payakumbuh' },
    { value: 'solok', label: 'Kota Solok' },
    { value: 'padang_panjang', label: 'Kota Padang Panjang' },
    { value: 'pariaman', label: 'Kota Pariaman' },
    { value: 'agam', label: 'Kab. Agam' },
    { value: 'tanah_datar', label: 'Kab. Tanah Datar' },
  ],
  riau: [
    { value: 'pekanbaru', label: 'Kota Pekanbaru' },
    { value: 'dumai', label: 'Kota Dumai' },
    { value: 'kampar', label: 'Kab. Kampar' },
    { value: 'rokan_hulu', label: 'Kab. Rokan Hulu' },
    { value: 'bengkalis', label: 'Kab. Bengkalis' },
    { value: 'siak', label: 'Kab. Siak' },
  ],
  kepulauan_riau: [
    { value: 'batam', label: 'Kota Batam' },
    { value: 'tanjungpinang', label: 'Kota Tanjungpinang' },
    { value: 'bintan', label: 'Kab. Bintan' },
    { value: 'karimun', label: 'Kab. Karimun' },
    { value: 'natuna', label: 'Kab. Natuna' },
  ],
  jambi: [
    { value: 'jambi', label: 'Kota Jambi' },
    { value: 'sungai_penuh', label: 'Kota Sungai Penuh' },
    { value: 'batanghari', label: 'Kab. Batanghari' },
    { value: 'muaro_jambi', label: 'Kab. Muaro Jambi' },
    { value: 'bungo', label: 'Kab. Bungo' },
  ],
  sumatera_selatan: [
    { value: 'palembang', label: 'Kota Palembang' },
    { value: 'prabumulih', label: 'Kota Prabumulih' },
    { value: 'pagar_alam', label: 'Kota Pagar Alam' },
    { value: 'lubuklinggau', label: 'Kota Lubuklinggau' },
    { value: 'ogan_komering_ulu', label: 'Kab. Ogan Komering Ulu' },
    { value: 'muara_enim', label: 'Kab. Muara Enim' },
    { value: 'banyuasin', label: 'Kab. Banyuasin' },
  ],
  kepulauan_bangka_belitung: [
    { value: 'pangkalpinang', label: 'Kota Pangkalpinang' },
    { value: 'bangka', label: 'Kab. Bangka' },
    { value: 'belitung', label: 'Kab. Belitung' },
    { value: 'bangka_tengah', label: 'Kab. Bangka Tengah' },
    { value: 'bangka_selatan', label: 'Kab. Bangka Selatan' },
  ],
  bengkulu: [
    { value: 'bengkulu', label: 'Kota Bengkulu' },
    { value: 'rejang_lebong', label: 'Kab. Rejang Lebong' },
    { value: 'bengkulu_utara', label: 'Kab. Bengkulu Utara' },
    { value: 'seluma', label: 'Kab. Seluma' },
  ],
  lampung: [
    { value: 'bandar_lampung', label: 'Kota Bandar Lampung' },
    { value: 'metro', label: 'Kota Metro' },
    { value: 'lampung_selatan', label: 'Kab. Lampung Selatan' },
    { value: 'lampung_tengah', label: 'Kab. Lampung Tengah' },
    { value: 'lampung_utara', label: 'Kab. Lampung Utara' },
    { value: 'way_kanan', label: 'Kab. Way Kanan' },
    { value: 'tanggamus', label: 'Kab. Tanggamus' },
  ],
  banten: [
    { value: 'serang', label: 'Kota Serang' },
    { value: 'cilegon', label: 'Kota Cilegon' },
    { value: 'tangerang', label: 'Kota Tangerang' },
    { value: 'tangerang_selatan', label: 'Kota Tangerang Selatan' },
    { value: 'kab_serang', label: 'Kab. Serang' },
    { value: 'kab_tangerang', label: 'Kab. Tangerang' },
    { value: 'lebak', label: 'Kab. Lebak' },
    { value: 'pandeglang', label: 'Kab. Pandeglang' },
  ],
  dki_jakarta: [
    { value: 'jakarta_pusat', label: 'Jakarta Pusat' },
    { value: 'jakarta_utara', label: 'Jakarta Utara' },
    { value: 'jakarta_barat', label: 'Jakarta Barat' },
    { value: 'jakarta_selatan', label: 'Jakarta Selatan' },
    { value: 'jakarta_timur', label: 'Jakarta Timur' },
    { value: 'kepulauan_seribu', label: 'Kab. Kepulauan Seribu' },
  ],
  jawa_barat: [
    { value: 'bandung', label: 'Kota Bandung' },
    { value: 'bekasi', label: 'Kota Bekasi' },
    { value: 'bogor', label: 'Kota Bogor' },
    { value: 'cimahi', label: 'Kota Cimahi' },
    { value: 'cirebon', label: 'Kota Cirebon' },
    { value: 'depok', label: 'Kota Depok' },
    { value: 'sukabumi', label: 'Kota Sukabumi' },
    { value: 'tasikmalaya', label: 'Kota Tasikmalaya' },
    { value: 'banjar', label: 'Kota Banjar' },
    { value: 'kab_bandung', label: 'Kab. Bandung' },
    { value: 'kab_bekasi', label: 'Kab. Bekasi' },
    { value: 'kab_bogor', label: 'Kab. Bogor' },
    { value: 'kab_cirebon', label: 'Kab. Cirebon' },
    { value: 'garut', label: 'Kab. Garut' },
    { value: 'indramayu', label: 'Kab. Indramayu' },
    { value: 'karawang', label: 'Kab. Karawang' },
    { value: 'purwakarta', label: 'Kab. Purwakarta' },
    { value: 'subang', label: 'Kab. Subang' },
    { value: 'sumedang', label: 'Kab. Sumedang' },
  ],
  jawa_tengah: [
    { value: 'semarang', label: 'Kota Semarang' },
    { value: 'solo', label: 'Kota Surakarta' },
    { value: 'magelang', label: 'Kota Magelang' },
    { value: 'salatiga', label: 'Kota Salatiga' },
    { value: 'pekalongan', label: 'Kota Pekalongan' },
    { value: 'tegal', label: 'Kota Tegal' },
    { value: 'banyumas', label: 'Kab. Banyumas' },
    { value: 'cilacap', label: 'Kab. Cilacap' },
    { value: 'demak', label: 'Kab. Demak' },
    { value: 'grobogan', label: 'Kab. Grobogan' },
    { value: 'jepara', label: 'Kab. Jepara' },
    { value: 'kebumen', label: 'Kab. Kebumen' },
    { value: 'klaten', label: 'Kab. Klaten' },
    { value: 'kudus', label: 'Kab. Kudus' },
    { value: 'purworejo', label: 'Kab. Purworejo' },
    { value: 'rembang', label: 'Kab. Rembang' },
    { value: 'sragen', label: 'Kab. Sragen' },
    { value: 'wonogiri', label: 'Kab. Wonogiri' },
    { value: 'wonosobo', label: 'Kab. Wonosobo' },
  ],
  di_yogyakarta: [
    { value: 'yogyakarta', label: 'Kota Yogyakarta' },
    { value: 'sleman', label: 'Kab. Sleman' },
    { value: 'bantul', label: 'Kab. Bantul' },
    { value: 'gunungkidul', label: 'Kab. Gunungkidul' },
    { value: 'kulon_progo', label: 'Kab. Kulon Progo' },
  ],
  jawa_timur: [
    { value: 'surabaya', label: 'Kota Surabaya' },
    { value: 'malang', label: 'Kota Malang' },
    { value: 'blitar', label: 'Kota Blitar' },
    { value: 'kediri', label: 'Kota Kediri' },
    { value: 'madiun', label: 'Kota Madiun' },
    { value: 'mojokerto', label: 'Kota Mojokerto' },
    { value: 'pasuruan', label: 'Kota Pasuruan' },
    { value: 'probolinggo', label: 'Kota Probolinggo' },
    { value: 'batu', label: 'Kota Batu' },
    { value: 'gresik', label: 'Kab. Gresik' },
    { value: 'sidoarjo', label: 'Kab. Sidoarjo' },
    { value: 'jember', label: 'Kab. Jember' },
    { value: 'banyuwangi', label: 'Kab. Banyuwangi' },
    { value: 'jombang', label: 'Kab. Jombang' },
    { value: 'lamongan', label: 'Kab. Lamongan' },
    { value: 'lumajang', label: 'Kab. Lumajang' },
    { value: 'tuban', label: 'Kab. Tuban' },
    { value: 'kab_malang', label: 'Kab. Malang' },
    { value: 'kab_kediri', label: 'Kab. Kediri' },
    { value: 'bojonegoro', label: 'Kab. Bojonegoro' },
  ],
  bali: [
    { value: 'denpasar', label: 'Kota Denpasar' },
    { value: 'badung', label: 'Kab. Badung' },
    { value: 'gianyar', label: 'Kab. Gianyar' },
    { value: 'tabanan', label: 'Kab. Tabanan' },
    { value: 'buleleng', label: 'Kab. Buleleng' },
    { value: 'karangasem', label: 'Kab. Karangasem' },
    { value: 'klungkung', label: 'Kab. Klungkung' },
    { value: 'bangli', label: 'Kab. Bangli' },
    { value: 'jembrana', label: 'Kab. Jembrana' },
  ],
  nusa_tenggara_barat: [
    { value: 'mataram', label: 'Kota Mataram' },
    { value: 'bima', label: 'Kota Bima' },
    { value: 'lombok_barat', label: 'Kab. Lombok Barat' },
    { value: 'lombok_tengah', label: 'Kab. Lombok Tengah' },
    { value: 'lombok_timur', label: 'Kab. Lombok Timur' },
    { value: 'sumbawa', label: 'Kab. Sumbawa' },
    { value: 'dompu', label: 'Kab. Dompu' },
  ],
  nusa_tenggara_timur: [
    { value: 'kupang', label: 'Kota Kupang' },
    { value: 'kab_kupang', label: 'Kab. Kupang' },
    { value: 'timor_tengah_selatan', label: 'Kab. Timor Tengah Selatan' },
    { value: 'flores_timur', label: 'Kab. Flores Timur' },
    { value: 'sikka', label: 'Kab. Sikka' },
    { value: 'ende', label: 'Kab. Ende' },
    { value: 'manggarai', label: 'Kab. Manggarai' },
  ],
  kalimantan_barat: [
    { value: 'pontianak', label: 'Kota Pontianak' },
    { value: 'singkawang', label: 'Kota Singkawang' },
    { value: 'kubu_raya', label: 'Kab. Kubu Raya' },
    { value: 'mempawah', label: 'Kab. Mempawah' },
    { value: 'sambas', label: 'Kab. Sambas' },
    { value: 'sanggau', label: 'Kab. Sanggau' },
    { value: 'ketapang', label: 'Kab. Ketapang' },
  ],
  kalimantan_tengah: [
    { value: 'palangka_raya', label: 'Kota Palangka Raya' },
    { value: 'kotawaringin_barat', label: 'Kab. Kotawaringin Barat' },
    { value: 'kotawaringin_timur', label: 'Kab. Kotawaringin Timur' },
    { value: 'kapuas', label: 'Kab. Kapuas' },
    { value: 'barito_selatan', label: 'Kab. Barito Selatan' },
    { value: 'barito_utara', label: 'Kab. Barito Utara' },
  ],
  kalimantan_selatan: [
    { value: 'banjarmasin', label: 'Kota Banjarmasin' },
    { value: 'banjarbaru', label: 'Kota Banjarbaru' },
    { value: 'banjar', label: 'Kab. Banjar' },
    { value: 'tabalong', label: 'Kab. Tabalong' },
    { value: 'tanah_laut', label: 'Kab. Tanah Laut' },
    { value: 'hulu_sungai_selatan', label: 'Kab. Hulu Sungai Selatan' },
    { value: 'hulu_sungai_utara', label: 'Kab. Hulu Sungai Utara' },
  ],
  kalimantan_timur: [
    { value: 'samarinda', label: 'Kota Samarinda' },
    { value: 'balikpapan', label: 'Kota Balikpapan' },
    { value: 'bontang', label: 'Kota Bontang' },
    { value: 'kutai_kartanegara', label: 'Kab. Kutai Kartanegara' },
    { value: 'berau', label: 'Kab. Berau' },
    { value: 'penajam_paser_utara', label: 'Kab. Penajam Paser Utara' },
  ],
  kalimantan_utara: [
    { value: 'tarakan', label: 'Kota Tarakan' },
    { value: 'bulungan', label: 'Kab. Bulungan' },
    { value: 'malinau', label: 'Kab. Malinau' },
    { value: 'nunukan', label: 'Kab. Nunukan' },
    { value: 'tana_tidung', label: 'Kab. Tana Tidung' },
  ],
  sulawesi_utara: [
    { value: 'manado', label: 'Kota Manado' },
    { value: 'bitung', label: 'Kota Bitung' },
    { value: 'tomohon', label: 'Kota Tomohon' },
    { value: 'kotamobagu', label: 'Kota Kotamobagu' },
    { value: 'minahasa', label: 'Kab. Minahasa' },
    { value: 'bolaang_mongondow', label: 'Kab. Bolaang Mongondow' },
  ],
  gorontalo: [
    { value: 'gorontalo', label: 'Kota Gorontalo' },
    { value: 'kab_gorontalo', label: 'Kab. Gorontalo' },
    { value: 'boalemo', label: 'Kab. Boalemo' },
    { value: 'pohuwato', label: 'Kab. Pohuwato' },
    { value: 'bone_bolango', label: 'Kab. Bone Bolango' },
  ],
  sulawesi_tengah: [
    { value: 'palu', label: 'Kota Palu' },
    { value: 'donggala', label: 'Kab. Donggala' },
    { value: 'poso', label: 'Kab. Poso' },
    { value: 'morowali', label: 'Kab. Morowali' },
    { value: 'banggai', label: 'Kab. Banggai' },
    { value: 'tolitoli', label: 'Kab. Tolitoli' },
  ],
  sulawesi_barat: [
    { value: 'mamuju', label: 'Kab. Mamuju' },
    { value: 'majene', label: 'Kab. Majene' },
    { value: 'polewali_mandar', label: 'Kab. Polewali Mandar' },
    { value: 'mamasa', label: 'Kab. Mamasa' },
    { value: 'pasangkayu', label: 'Kab. Pasangkayu' },
  ],
  sulawesi_selatan: [
    { value: 'makassar', label: 'Kota Makassar' },
    { value: 'parepare', label: 'Kota Parepare' },
    { value: 'palopo', label: 'Kota Palopo' },
    { value: 'gowa', label: 'Kab. Gowa' },
    { value: 'bone', label: 'Kab. Bone' },
    { value: 'luwu', label: 'Kab. Luwu' },
    { value: 'maros', label: 'Kab. Maros' },
    { value: 'pangkajene', label: 'Kab. Pangkajene dan Kepulauan' },
    { value: 'wajo', label: 'Kab. Wajo' },
    { value: 'bulukumba', label: 'Kab. Bulukumba' },
  ],
  sulawesi_tenggara: [
    { value: 'kendari', label: 'Kota Kendari' },
    { value: 'baubau', label: 'Kota Baubau' },
    { value: 'kolaka', label: 'Kab. Kolaka' },
    { value: 'konawe', label: 'Kab. Konawe' },
    { value: 'muna', label: 'Kab. Muna' },
    { value: 'buton', label: 'Kab. Buton' },
  ],
  maluku: [
    { value: 'ambon', label: 'Kota Ambon' },
    { value: 'tual', label: 'Kota Tual' },
    { value: 'maluku_tengah', label: 'Kab. Maluku Tengah' },
    { value: 'buru', label: 'Kab. Buru' },
    { value: 'seram_bagian_barat', label: 'Kab. Seram Bagian Barat' },
    { value: 'maluku_tenggara', label: 'Kab. Maluku Tenggara' },
  ],
  maluku_utara: [
    { value: 'ternate', label: 'Kota Ternate' },
    { value: 'tidore_kepulauan', label: 'Kota Tidore Kepulauan' },
    { value: 'halmahera_barat', label: 'Kab. Halmahera Barat' },
    { value: 'halmahera_utara', label: 'Kab. Halmahera Utara' },
    { value: 'halmahera_selatan', label: 'Kab. Halmahera Selatan' },
  ],
  papua_barat: [
    { value: 'manokwari', label: 'Kab. Manokwari' },
    { value: 'sorong', label: 'Kota Sorong' },
    { value: 'kab_sorong', label: 'Kab. Sorong' },
    { value: 'fak_fak', label: 'Kab. Fak-Fak' },
    { value: 'teluk_bintuni', label: 'Kab. Teluk Bintuni' },
  ],
  papua: [
    { value: 'jayapura', label: 'Kota Jayapura' },
    { value: 'kab_jayapura', label: 'Kab. Jayapura' },
    { value: 'merauke', label: 'Kab. Merauke' },
    { value: 'nabire', label: 'Kab. Nabire' },
    { value: 'biak_numfor', label: 'Kab. Biak Numfor' },
    { value: 'mimika', label: 'Kab. Mimika' },
  ],
  papua_selatan: [
    { value: 'merauke', label: 'Kab. Merauke' },
    { value: 'boven_digoel', label: 'Kab. Boven Digoel' },
    { value: 'mappi', label: 'Kab. Mappi' },
    { value: 'asmat', label: 'Kab. Asmat' },
  ],
  papua_tengah: [
    { value: 'nabire', label: 'Kab. Nabire' },
    { value: 'paniai', label: 'Kab. Paniai' },
    { value: 'mimika', label: 'Kab. Mimika' },
    { value: 'puncak_jaya', label: 'Kab. Puncak Jaya' },
    { value: 'puncak', label: 'Kab. Puncak' },
  ],
  papua_pegunungan: [
    { value: 'jayawijaya', label: 'Kab. Jayawijaya' },
    { value: 'pegunungan_bintang', label: 'Kab. Pegunungan Bintang' },
    { value: 'tolikara', label: 'Kab. Tolikara' },
    { value: 'yalimo', label: 'Kab. Yalimo' },
  ],
  papua_barat_daya: [
    { value: 'sorong', label: 'Kota Sorong' },
    { value: 'kab_sorong', label: 'Kab. Sorong' },
    { value: 'raja_ampat', label: 'Kab. Raja Ampat' },
    { value: 'tambrauw', label: 'Kab. Tambrauw' },
    { value: 'maybrat', label: 'Kab. Maybrat' },
  ],
}
